import type { Metadata } from "next";
import "./globals.css";
import NavItems from "./component/nav/NavItem.tsx"
export const metadata: Metadata = {
  title: "Bca-classroom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <NavItems/>
      <body>{children}</body>
    </html>
  );
}
